# Generated by Django 6.0 on 2025-12-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
